/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Customer]
(
[Id] [int] NULL,
[Name] [varchar] (50) NULL,
[AccountNumber] [varchar] (50) NULL,
[AccountType] [varchar] (2) NULL
)
GO
